<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <script src="/assets/js/bootstrap.bundle.min.js"></script>
</head>

<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>

                    <!-- Вывод сообщений об ошибках -->
                    <?php if (!empty($errors)): ?>
                        <div class="alert alert-danger">
                            <?= htmlspecialchars(implode('; ', $errors)) ?>
                        </div>
                    <?php endif; ?>

                    <form action="/urls" method="post" class="row" novalidate>
                        <div class="col-8">
                            <label for="url" class="visually-hidden">Url для проверки</label>
                            <input type="text" name="url[name]" id="url" 
                                value="<?= htmlspecialchars($entered_url ?? '') ?>" 
                                class="form-control form-control-lg <?= !empty($incorrectUrlError) || !empty($emptyUrlError) ? 'is-invalid' : '' ?>" 
                                placeholder="https://www.example.com" required>

                            <!-- Отображение сообщения об ошибке, если URL пустой -->
                            <?php if (!empty($emptyUrlError)): ?>
                                <div class="invalid-feedback">URL не должен быть пустым</div>
                            <?php endif; ?>

                            <!-- Отображение сообщения об ошибке, если URL некорректный -->
                            <?php if (!empty($incorrectUrlError)): ?>
                                <div class="invalid-feedback">Некорректный URL</div>
                            <?php endif; ?>
                        </div>
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-lg" id="submit-button">Проверить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>

</html>