<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Детали URL</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <h1 class="mt-5">Детали URL</h1>
    <table class="table" data-test="url">
        <tr>
            <th>ID</th>
            <td><?= htmlspecialchars($url['id']) ?></td>
        </tr>
        <tr>
            <th>URL</th>
            <td><?= htmlspecialchars($url['name']) ?></td>
        </tr>
        <tr>
            <th>Создан</th>
            <td><?= htmlspecialchars($url['created_at']) ?></td>
        </tr>
    </table>
</div>
</body>
</html>