<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сайты</title>
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <script src="/assets/js/bootstrap.bundle.min.js"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <!-- Таблица со списком адресов -->
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($urls as $url): ?>
                        <tr>
                            <td><?= htmlspecialchars($url['id'], ENT_QUOTES, 'UTF-8') ?></td>
                            <td><a href="/urls/<?= htmlspecialchars($url['id'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($url['name'], ENT_QUOTES, 'UTF-8') ?></a></td>
                            <td><?= htmlspecialchars($url['last_check_at'] ?? 'Нет проверок', ENT_QUOTES, 'UTF-8') ?></td>
                            <td><?= htmlspecialchars($url['last_status_code'] ?? 'Нет проверок', ENT_QUOTES, 'UTF-8') ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>
</html>